name: Pre-commit checks

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: fmt check
        run: make fmt-check

      - name: unit tests
        run: make test

      - name: integration tests
        run: make test
